version: '3.9'

services:
  consumer:
    image: spotify/kafka
    container_name: consumer
    # environment:
    #   ADVERTISED_HOST: \`docker-machine ip \\`docker-machine active\\``
    #   ADVERTISED_PORT: 9092
    networks:
      - kafka-network
  producer:
    image: spotify/kafka
    container_name: producer
    networks:
      - kafka-network
  kafka:
    image: spotify/kafka
    container_name: kafka
    ports:
      - 2181:2181
      - 9092:9092
      - 9093:9093
      - 9094:9094
    networks:
      - kafka-network
    volumes:
      - ./config/server-1.properties:/opt/kafka_2.11-0.10.1.0/config/server-1.properties
      - ./config/server-2.properties:/opt/kafka_2.11-0.10.1.0/config/server-2.properties
      - ./logs/kafka-logs-1:/tmp/kafka-logs-1
      - ./logs/kafka-logs-2:/tmp/kafka-logs-2
      - ./scripts:/scripts
      - ./file.log:/file.log
    # environment:
    #   ADVERTISED_HOST: \`docker-machine ip \\`docker-machine active\\``
    #   ADVERTISED_PORT: 9092
networks:
  kafka-network:
